/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.KevinZach.spring.action;

import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.util.Assert;

import com.KevinZach.spring.form.Wife2Form;
import com.KevinZach.spring.orm.Wife;
import com.KevinZach.spring.orm.IWifeService;

/**
 * MyEclipse Struts Creation date: 06-30-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/wife2" name="wife2Form" input="/form/listWife2.jsp"
 *                scope="request" validate="true"
 */
public class Wife2Action extends Action {

	private IWifeService wifeService;

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		Wife2Form wife2Form = (Wife2Form) form;

		if ("add".equals(wife2Form.getAction()))
			return this.add(mapping, form, request, response);

		return this.list(mapping, form, request, response);
	}

	public ActionForward add(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		Wife2Form wife2Form = (Wife2Form) form;

		Assert.hasLength(wife2Form.getName(), "名字不能为 null");

		Wife wife = new Wife();
		wife.setName(wife2Form.getName());
		wife.setCreatedDate(new Date());

		wifeService.createWife(wife);

		return this.list(mapping, form, request, response);
	}

	public ActionForward list(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		List<Wife> wifeList = wifeService.listWives();

		request.setAttribute("wifeList", wifeList);

		return mapping.findForward("list");
	}

	public IWifeService getWifeService() {
		return wifeService;
	}

	public void setCatService(IWifeService wifeService) {
		this.wifeService = wifeService;
	}
}